### PR TITLE
Node 8+ support

### PR DESCRIPTION
**Pull request by Algunenano**
I was getting this error when building from source with node 10:
```
  CXX(target) Release/obj.target/zipfile/src/node_zipfile.o
In file included from ../node_modules/nan/nan.h:190,
                 from ../src/node_zipfile.hpp:9,
                 from ../src/node_zipfile.cpp:1:
../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’
../node_modules/nan/nan_maybe_43_inl.h:88:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
```

Since installing it using the precompiled module works I guess that someone did it manually at some point.

### CODE REVIEW

**Comment by springmeyer** [comment]
Yes, I backfilled a binary for node v8 via #78. Your PR here already looks better than #78, so please carry on and ping if you need a review.

**Comment by Algunenano** [comment]
I see that you were also updating dev dependencies so I've added some commits to do that shutting up `npm audit` in the process.

Seems like coveralls refuses to work properly (also locally) and the Windows build is broken (which is a big pain to test since I have to just push and wait for appveyor to do its thing).

**Comment by springmeyer** [comment]
> I see that you were also updating dev dependencies so I've added some commits to do that shutting up npm audit in the process.

👍 

> Seems like coveralls refuses to work properly (also locally)

Yeah. I've given up on coveralls and been moving to codecov. I'd been planning to port this repo over to codecov by copying the travis logic at https://github.com/mapbox/node-cpp-skel, but have not gotten to it.

For now, to get you unblocked I propose just removing the coveralls job.

> and the Windows build is broken (which is a big pain to test since I have to just push and wait for appveyor to do its thing).

Ugh, sorry, yeah. Looks like I missed merging https://github.com/mapbox/node-zipfile/pull/74, which would have had the module in a slightly better place as far as windows (that is similar to node-gdal).

**Comment by Algunenano** [comment]
Well played Windows, I give up. I'm open to ideas on how to fix either of the 2 different errors (node 4 in 32b, node 10 using both 32/64 bits).

**Comment by springmeyer** [comment]
No ideal how to fix windows. Thanks for trying. Going to merge this and let it be broken. Ticketed at #80

**Pull request merged**
